name: MineStock
version: 0.1.0pre-alpha 132892
description: A simple stock-trading plugin for Bukkit/Vault servers
author: abujaki21
website: http://abujaki21.github.io/minestock/
main: io.github.abujaki.minestock.MineStock
depend: [Vault]
commands:
  stockbuy:
    description: Place a buy order for a stock
    usage: /stockbuy <stock> <amount> <priceEach>
    permission: minestock.buy
    permission-message: You do not have permission to buy stocks from the market.
  stocksell:
    description: Sell stocks on the stock market
    usage: /stocksell <stock> <amount> <priceEach>
    permission: minestock.sell
    permission-message: You do not have permission to buy stocks from the market.
permissions:
  minestock.basic:
    description: Allows a user to conduct basic transactions in the stock market
    default: true
    children:
      minestock.buy: true
      minestock.sell: true
  minestock.buy:
    description: Allows a user to buy stocks from the stock market
  minestock.sell:
    description: Allows a user to sell stocks on the stock market
